ARG BASE_IMAGE=nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04
FROM ${BASE_IMAGE}

ENV PATH="/usr/local/cuda/bin:$PATH"
ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"
ENV MMCV_WITH_OPS=1
ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0 7.5 8.0 8.6+PTX 8.9+PTX 9.0+PTX" \
    TORCH_NVCC_FLAGS="-Xfatbin -compress-all" \
    FORCE_CUDA="1"
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
        libsm6 libxext6 git ninja-build libglib2.0-0 libxrender-dev libxext6 \
        gcc libgl1 \
        ca-certificates python3-dev python3-pip python3-tk git wget ninja-build libgl1

RUN pip3 install torch==2.0.0 torchvision==0.15.1 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118

RUN pip3 install --no-cache-dir --upgrade pip wheel setuptools
RUN pip3 install cython xtcocotools
# RUN pip3 install mmcv==2.1.0 -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.0/index.html

# COPY requirements /opt/tmp/requirements
# COPY requirements.txt /opt/tmp/requirements.txt
# RUN cd /opt/tmp && pip3 install -r requirements.txt

WORKDIR /opt/libs
RUN git clone https://github.com/open-mmlab/mmcv.git
RUN cd mmcv && git checkout tags/v2.1.0 && pip3 install -r requirements/optional.txt
RUN cd mmcv && pip3 install -e . -v
# RUN cd mmcv && python3 .dev_scripts/check_installation.py

RUN pip install openmim
RUN mim install mmengine
RUN mim install mmdet
RUN pip install mmcv-full
